### ISSUE TITLE
Possible license issue

### ISSUE THREAD

**Issue by JayFoxRox** [gregzaal/Texture-Haven#1]
This code is licensed under the GPLv3. Normally that license is chosen to ensure that modifications of the code remain in the public (as source-code), if the product is made usable (as binary).

However, for websites, the GPLv3 does not reach this goal.
The binary (the PHP code) is never distributed if the code runs server-side, so the GPLv3 does not give users the right to ask for source-code.

The Affero GPL (AGPLv3) was designed to handle this.
Also see https://en.wikipedia.org/wiki/Affero_General_Public_License

If the intention was to just make the code public (as with the rest of the sites content), then consider slapping CC0, BSD or MIT license on it instead, to be even less restrictive.

**Comment by gregzaal** [comment]
Thanks for pointing this out, I'll look into it 👍
