### ISSUE TITLE
API doesn't expose all information

### ISSUE THREAD

**Issue by JayFoxRox** [gregzaal/Texture-Haven#4]
The functions in https://github.com/gregzaal/Texture-Haven/blob/master/php/tex1_list.php and https://github.com/gregzaal/Texture-Haven/blob/master/php/json_list.php do not list some information:

- Author (although all of them are by Rob Tuytel at this point)
- License (although all of them are CC0 at this point)
- Category names
- Human readable category names
- Number of downloads
- Publish date

Possibly other information, too.
This would be useful when interfacing with the website from within a texture asset manager (although the metadata can be scraped per-texture from the HTML, and would likely be cached locally anyway).

**Comment by gregzaal** [comment]
Based on the docs Lennart sent me for textures.one not all of that info is required, though I will be adding some of it after I've [unified the codebase](https://github.com/gregzaal/Haven-Core) for 3D Model Haven. If anyone is working on an asset manager that integrates texturehaven and needs some more info, they're welcome to contact me.
