### ISSUE TITLE
Texture view does not show human readable category name

### ISSUE THREAD

**Issue by JayFoxRox** [gregzaal/Texture-Haven#5]
When viewing a texture, the internal category name is shown, instead of the human readable one that's shown in the navigation.

**Comment by gregzaal** [comment]
"Human readable" categories on texturehaven are literally just title-case versions of the lower-case ones. Showing them in lower- or title-case is just a style choice, and personally I prefer "Tags: dark, red, seamless" over "Tags: Dark, Red, Seamless".

**Comment by JayFoxRox** [comment]
> "Human readable" categories on texturehaven are literally just title-case versions of the lower-case ones.

I didn't realize.
Interesting. Thanks for explaining!

> Showing them in lower- or title-case is just a style choice, and personally I prefer "Tags: dark, red, seamless" over "Tags: Dark, Red, Seamless".

I agree regarding tags (should be lowercase). For the category I'd still suggest to use uppercase for display, and only lowercase for URLs, to make it more consistent.
