### ISSUE TITLE
FAQ page is broken

### ISSUE THREAD

**Issue by Georift** [gregzaal/Texture-Haven#8]
When I visit `faq.php` I get the following:
```
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/texhav/texturehaven.com/core/core.php on line 837
```

I attempted to try my hand at fixing this issue but I noticed that `core/core.php` file is not included in this repository.

I'm a web developer who is getting into blender, if there is anything I can do to help out on the software side let me know. :)

**Comment by Georift** [comment]
Just noticed the `core.php` file is explicitly excluded in the git ignore, is this where we keep things that cannot be disclosed?

**Comment by gregzaal** [comment]
Ah thanks, just forgot to add the table in the DB :)

**Comment by gregzaal** [comment]
> 
> 
> Just noticed the `core.php` file is explicitly excluded in the git ignore, is this where we keep things that cannot be disclosed?

Since launching 3dmodelhaven I made a core repo for all the code shared between the sites: https://github.com/gregzaal/Haven-Core

I just updated the readme for this (TH) repo with some more build instructions.

**Comment by Georift** [comment]
Ah awesome, good idea with extracting the core. Thanks for checking out my issue.
