### ISSUE TITLE
Is there any form of public API?

### ISSUE THREAD

**Issue by tebjan** [gregzaal/Texture-Haven#9]
Hello, I am looking for help implementing a tool that can automatically download and import textures from texturehaven.com and create a material for the free and open-source game engine Stride (formerly Xenko): https://stride3d.net

So can you give me any advice on how to enumerate the different materials that are present on the page? ideally with category/tag information to create a structured view.

All credits will be shown, of course...

**Comment by gregzaal** [comment]
We have a json list with all assets, including categories, tags, resolutions and format variations: https://texturehaven.com/php/assetninja.php?v=1.0

That list will automatically update with the latest textures as they're published. The `version` tag (set by the `?v=1.0` in the URL) is there to guarantee a consistent JSON structure so you can use this page directly in your code.

If you or your company (or anyone else stumbling upon this thread) benefits financially from our service with such an integration, consider [supporting us on Patreon](https://www.patreon.com/TextureHaven/overview) to help us continue to provide these textures for free and to grow the quality and variety available.

**Comment by tebjan** [comment]
Great, thanks for the swift response!

Getting the list works great so far. Is it also possible to get the preview images somewhere?

I'll definitely include a link to your Patreon. Currently, this is just a home project...

**Comment by gregzaal** [comment]
The only predictable URL we have for the previews is this: `https://texturehaven.com/files/tex_images/spheres/X.jpg` where X is the key of each asset in that json list.

**Comment by tebjan** [comment]
Thanks for the help, I'll keep you posted if I get anything to work.
